### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Kassandra-QA** [Kassandra-QA/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Oleksandra-Pidchibii** [comment]
February 2020 - till current time 
NASU Institute of Electrodynamics 
Engineer (1st  category)	

•	Carrying out scientific research in cooperation with engineering, scientific and technical personnel.
•	Modeling electrostatic process and physical calculations of experimental installations using finite element analysis package COMSOL Multiphysics
•	Experimental data processing (Excel, Matlab)
•	Preparation and design of scientific publications (articles) and reports

June 2016 - December 2017
LeBoutique
Customer Support	 

•	Supporting users in the mode of incoming calls
•	Analyzing problems encountered by the user and search for solutions to the problem
•	Communicating with other departments of the company

September 2011 - December 2020
•	NTUU “Igor Sikorsky Kyiv Polytechnic Institute”, Master’s degree – Metrology and Information-Measuring Technology.
