### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Kassandra-QA** [Kassandra-QA/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Oleksandra-Pidchibii** [comment]
LANGUAGES
Українська Русский English

SKILLS
HTML, CSS, Windows, SQL (MySQL, DBeaver),  TestLinke, Mantis, Trello

CHARACTER
Organized Sociable Quick-Learn Troubleshoot Cheerful

LIKES
Coffee, fantasy and fantastic movies/books, PC/mobile/table games, skating
